### ISSUE TITLE
[FEATURE]: As a shopper, I want the search box to have an animated placeholder

### ISSUE THREAD

**Issue by herrardo** [empathyco/x#385]
### How can the project be improved?

To have an animated placeholder showing different messages to inspire the shopper to type different types of queries.

https://user-images.githubusercontent.com/4663897/160593353-64ff623c-af1f-4957-bab3-948efa45d839.mov

Even though in the video only one part of the string is animated, the idea is to animate the whole string to make things easier. So `find` won't be in a fixed position and will move with the rest of the string.

#### Hover scenario
Given a shopper who is going to type in the search box
when the user hovers the search box
then the placeholder is animated showing different messages
when the user clicks on the search box and the input get focused
then the placeholder disappears to start typing.

#### Normal scenario
Given a shopper who is going to type in the search box
then the placeholder is animated showing different messages
when the user clicks on the search box and the input get focused
then the placeholder disappears to start typing.

### Proposed solution

An idea could be to create a `SearchInputPlaceholder` component that can coexist with the [`SearchInput`](https://github.com/empathyco/x/blob/main/packages/x-components/src/x-modules/search-box/components/search-input.vue) component.

### Customizations supported

- The text of the messages have to be configurable
- The number of different texts is configurable
- The animation can happen on hover
- The animation can happen before the hover

### Additional information

This is the module where this task has to be done: https://github.com/empathyco/x/tree/main/packages/x-components/src/x-modules/search-box

[SearcInput documentation
](https://docs.empathy.co/develop-empathy-platform/ui-reference/components/search-box/x-components.search-input.html)

Have a look at the [Contributing Guidelines](https://github.com/empathyco/x/blob/main/.github/CONTRIBUTING.md) ;)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by jtomasdias00** [comment]
Hi @herrardo 

My colleague @brunorodrigues1999 and I are students at the masters program in software engineering at FEUP (https://paginas.fe.up.pt/~estudar/mesw/). As part of evaluating one of our curricular units, we need to choose an open-source project and fix an issue. We would like to know if we could help with this issue? Thanks!

**Comment by herrardo** [comment]
Yes sure @jtomasdias00 and @BrunoRodrigues1999!

Have a look to the [Contrib Guidelines](https://github.com/empathyco/x/blob/main/.github/CONTRIBUTING.md) first

**Comment by herrardo** [comment]
Good morning @jtomasdias00 Are you guys still working on this? Just let us know if you need something.

**Comment by BrunoRodrigues1999** [comment]
> Good morning @jtomasdias00 Are you guys still working on this? Just let us know if you need something.

Hi @herrardo , we already started working on the project, neverthless we are some challenges when setting up the project 
![Captura de ecrã 2022-05-09 160453](https://user-images.githubusercontent.com/92938770/167439697-14d92291-59bb-48e7-9e3e-2daf52dc1bd0.png)

**Comment by herrardo** [comment]
> > Good morning @jtomasdias00 Are you guys still working on this? Just let us know if you need something.
> 
> Hi @herrardo , we already started working on the project, nevertheless we are having some issues when setting up the same ![Captura de ecrã 2022-05-09 160453](https://user-images.githubusercontent.com/92938770/167439697-14d92291-59bb-48e7-9e3e-2daf52dc1bd0.png)

Sorry guys! Didn't realize about the comment. Try to change to node v14.18.0

**Comment by BrunoRodrigues1999** [comment]
Hi @herrardo . After applying the suggested changes there is still some issues
![Captura de ecrã 2022-05-13 163801](https://user-images.githubusercontent.com/92938770/168318562-f2ba9991-5961-406e-b29f-1f97ae79275c.png)

**Comment by herrardo** [comment]
Restore to initial state and Try `npm ci` instead of `npm install` @BrunoRodrigues1999 

Otherwise I will connect on discord on Monday ;)

**Comment by BrunoRodrigues1999** [comment]
Still not there yet. Discord it is...
![Captura de ecrã 2022-05-14 090352](https://user-images.githubusercontent.com/92938770/168416939-e557e02f-caec-4498-aace-f66ca8e99903.png)

**Comment by herrardo** [comment]
@BrunoRodrigues1999  We have done some research and there might be a problem with the build in Windows systems. Please try to delete the `node_modules` folder, and the `package-lock.json file,` and then do `npm install` to see if that solves the problem. In another case, I will open an issue for the team to review the build in Windows.

**Comment by BrunoRodrigues1999** [comment]
Hi @herrardo , even deleting the ```package-lock.json``` didn't do the trick. Seems to be an issue from your side

**Comment by herrardo** [comment]
It is. So sorry guys, I am opening an issue to correct it.

**Comment by herrardo** [comment]
Bug created https://github.com/empathyco/x/issues/492
And PR to solve it https://github.com/empathyco/x/pull/493

Thanks to @JaviIG :)

@BrunoRodrigues1999 You can merge the branch of the PR #493  in your branch to see if it solves your problem if you want to try before the PR is approved.

**Comment by BrunoRodrigues1999** [comment]
Hi @herrardo , i've just cloned @JaviIG repo with the fix. It indeed solved the ```npm install``` problem that we had.I' ve also ran ```npm run build```. After that i ```npm run serve``` and got the following...
![image](https://user-images.githubusercontent.com/92938770/168761557-b44642b6-aa6f-492b-9d9d-9cbb6a27955b.png)
Don't know if I'm in the right path to run the project in localhost.

**Comment by herrardo** [comment]
When running `npm run serve` at the root of the project you are launching the server for each one of the [packages](https://github.com/empathyco/x/tree/main/packages) that have a server associated.

To just run the X Components, which is the project you are interested in to develop the feature, you can run `npm run serve` setting the `x-components` folder as the working directory in the terminal as explained in the [x-components README](https://github.com/empathyco/x/blob/main/packages/x-components/README.md)

**Comment by alonsogarciapablo** [comment]
Hey!

I built a prototype to play with this idea (and the Animations API):

![animated-placeholder](https://user-images.githubusercontent.com/390398/176867959-588a9700-d8d3-47ff-9a13-b32c9ea700eb.gif)

code: https://codepen.io/alonsogarciapablo/pen/ExExewx

Some considerations:

- Given that users can navigate to the search input using the keyboard, I think it'd be useful to animate the placeholder when the search input has the focus (instead of relying on the mouse only).
- It would be useful to provide different animations. I implemented slide in/out and fade in/out, but more animations could be implemented (eg: a typewriter effect, as in https://remoteok.com/).
- Animations should also be configurable (eg: the duration/speed, etc.).
- It would be great to provide a way to define custom animations.

Before this gets implemented, it would be useful to agree on what the interface for the `SearchInputPlaceholder` component will look like. Some questions: How will someone pass the different placeholders? How will someone configure the animation(s)? Will this component have to be used inside the `SearchInput` (eg: in a slot) so that it gets automagically positioned on top of the input or should it be used outside (like the `ClearSearchInput`) and developers should "manually" position it on top of the `SearchInput`?

**Comment by alvarodE** [comment]
This issue is being closed by implementing a new [SearchInputPlaceholder](https://github.com/empathyco/x/blob/main/packages/x-components/src/x-modules/search-box/components/search-input-placeholder.vue) component as part of the SearchBox XModule.
An example of how to use it can be found [here](https://github.com/empathyco/x/blob/main/packages/x-components/src/views/home/Home.vue#L112).

The new component is avaliable from [@empathyco/x-components@3.0.0-alpha.196](https://github.com/empathyco/x/compare/@empathyco/x-components@3.0.0-alpha.195...@empathyco/x-components@3.0.0-alpha.196) (2022-10-19).
