### ISSUE TITLE
[FEATURE]: tagging support on banners

### ISSUE THREAD

**Issue by AdrianArenal** [empathyco/x#775]
### How can the project be improved?

At motive, we want to track clicks on banners. We want to take advantage of the logic already implemented on the x-component side so during the development of this feature we find out that the Banner model accept a `tagging` structure, but it is not working (there's not a request performed when clicking a banner).

### How can this be solved?

As far as we looked into it, we found that there's no wiring connection between the banner click event and the tagging config of each banner.

We were able to found a solution on our side, overriding the tagging wiring config and performing the tagging request on our own.

However, we think that this behaviour may fit on product side, so we will be able to decide wether if we want tagging on banners related to the `tagging` config of each banner.

### Proposed solution

Create a wire in which we can perform a tagging request IF there's a `tagging` config on the banner clicked.
The event emited to x when clicking a banner is `UserClickedABanner`.

### Additional information

Our own solution:

```ts
export const taggingOptions: XModulesOptions['tagging'] = {
  wiring: {
    ...
    UserClickedABanner: {
      trackBannerWire: filter(
        namespacedWireDispatch('tagging')(
          'track',
          ({ eventPayload: { tagging }, metadata: { location } }) => {
            const taggingInfo: TaggingRequest = tagging['click'];
            taggingInfo.params.location = location as string;
            return taggingInfo;
          }
        ),
        ({ eventPayload: { tagging } }) => !!tagging?.['click']
      )
    }
  }
};
```

and our banner object mapped has something like:
```ts
({
    ...
    tagging: {
      click: {
        url: `URL OF TAGGING SERVICE FOR A BANNER CLICK`,
        params: { ... }
      }
    }
 })
  ```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by javieri-empathy** [comment]
I would say that we missed this for both banners and promotions, since the demo  platform API that we are using does not return them.
It is easy to solve. We have some private helpers that are doing what you propose to add, so it should be even easier.

The only point that we need to be cautious about is with the platform adapter implementation, as it is currently mapping invalid tagging objects even if there is no tagging response
![image](https://user-images.githubusercontent.com/68222542/195340562-4a7f87d9-fe39-4bd3-aac9-abb3b9e55399.png)
![image](https://user-images.githubusercontent.com/68222542/195341062-12627aa7-2946-49dd-9898-feed97390872.png)
https://github.com/empathyco/x/blob/main/packages/x-adapter-platform/src/schemas/models/banner.schema.ts#L13

**Comment by herrardo** [comment]
@javieri-empathy @AdrianArenal I see there is already a Motive PR merged about this topic, could we close this issue?

**Comment by JaviIG** [comment]
Which issue do you mean @herrardo? I can't see the banner or promoted tracking working

**Comment by AdrianArenal** [comment]
@herrardo We merged our custom solution so we have the banners tagging structure added on our side, but we would prefer having it by default on each Banner model retrieved by X.

**Comment by herrardo** [comment]
We'll open a Pull  Request soon as ask you to review it ;)

cc @AdrianArenal @fernandossmm
